MONGODB_HOST: mongodb.joindevops.online
REDIS_HOST: redis.joindevops.online
CATALOGUE_HOST: catalogue.joindevops.online
MYSQL_HOST: mysql.joindevops.online
CART_HOST: cart.joindevops.online
RABBITMQ_HOST: rabbitmq.joindevops.online
USER_HOST: user.joindevops.online
