- name: Copy mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: installing mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present
- name: starting and enabling mongodb
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes  
- name: update ip address from 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1
    replace: 0.0.0.0
- name: restarting mongodb
  ansible.builtin.service:
    name: mongod
    state: restarted