- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup    